import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Home from '../components/home'


export default function Page() {
  return (
    <div >
      <Head>
        <title>Albad Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Home />
      </main>

      
    </div>
  )
}
